### ISSUE TITLE
Function percentage-to-decimal Issue

### ISSUE THREAD

**Issue by bravocado** [timhettler/compass-photoshop-gradient-overlay#4]
hello, i'm new to SASS. So, really sorry if i'm misunderstanding your documentation. I've found an invalid value because of percentage-to-decimal function.

i take your simple example

``` scss
.class {
background-image: linear-gradient(0deg, #000000 0%, #ffffff 100%);
}
```

and rendered like this

``` css
background-image: linear-gradient(0deg, #000000 0, #ffffff 1);
```

and the gradient will not show up.

I do a quick fix, i have to delete your percentage-to-decimal function on $stop.
